pages:
  - name: Services
    columns:
      - size: full
        widgets:
          - type: bookmarks
            groups:
              - title: Media Management
                links:
                  - title: Jellyfin
                    description: Media Server
                    url: http://192.168.0.50:8096
                  - title: Radarr
                    description: Movie Management
                    url: http://192.168.0.50:7878
                  - title: Sonarr
                    description: TV Shows Management
                    url: http://192.168.0.50:8989
                  - title: Bazarr
                    description: Subtitles Management
                    url: http://192.168.0.50:6767
                  - title: Jellyseerr
                    description: Media Requests
                    url: http://192.168.0.50:5055

              - title: Download & Indexing
                links:
                  - title: qBittorrent
                    description: Torrent Client
                    url: http://192.168.0.50:5080
                  - title: Prowlarr
                    description: Indexer Manager
                    url: http://192.168.0.50:9696
                  - title: FlareSolverr
                    description: Cloudflare Proxy
                    url: http://192.168.0.50:8191

              - title: Recommendations & Monitoring
                links:
                  - title: Recommendarr
                    description: Media Recommendations
                    url: http://192.168.0.50:3000
                  - title: Beszel
                    description: System Monitoring
                    url: http://192.168.0.50:8090

  # Add more pages here:
  # - name: Your page name
  #   columns:
  #     - size: small
  #       widgets:
  #         # Add widgets here

  #     - size: full
  #       widgets:
  #         # Add widgets here

  #     - size: small
  #       widgets:
  #         # Add widgets here